name: Update Fly.io Dashboard
on:
  schedule:
    - cron: '0 3 * * 2'
  workflow_dispatch:

jobs:
  update_data:
    name: Update salmon and orca data 
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Setup Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: mkdir -p ~/.cache/pip
      - name: Setup Flyio
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy fly 
        env: 
          FLY_API_TOKEN: ${{ secrets.FLYIO_TOKEN }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: flyctl deploy --remote-only
