name: Update Fly.io Dashboard
on:
  schedule:
    - cron: '0 3 * * 2'
  workflow_dispatch:

jobs:
  update_data:
    name: Update salmon and orca data 
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup SSH for private repo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TWM_SECRET }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Checkout private twm_data repo
        run: |
          git clone git@github.com:liu-zoe/twm_data.git data/twm_data  
      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: mkdir -p ~/.cache/pip
      - name: Setup Flyio
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy fly 
        env: 
          FLY_API_TOKEN: ${{ secrets.FLYIO_TOKEN }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: flyctl deploy --remote-only
