name: Update Data
on:
  schedule:
    - cron: '0 1 * * 2'
  workflow_dispatch:

jobs:
  update_data:
    name: Update salmon and orca data 
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
        
      - name: Setup Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install Dependencies 
        run: pip install -r requirements.txt
        
      - name: Run Script and Update Data 
        env: 
          ACARTIA_TOKEN: ${{ secrets.ACARTIA_TOKEN }}
        run: python scraper.py

      - name: Commit and Push Changes
        run: | 
          git config --local user.email "zoelzh@gmail.com"
          git config --local user.name "Zoe Liu"
          git add ./data/acartia/srkw_2024.csv ./data/foschinook/fos2024.csv ./data/bonchinook/bon2024.csv
          git commit -m "Updated data with GitHub Actions"
          git push origin main
